import type { Metadata } from "next";
import { pageMeta } from "@/lib/site-url";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, GithubLogo } from "@phosphor-icons/react/dist/ssr";
import { TechRow } from "@/components/tech-logo";
import { caseStudies } from "@/content/site";
import { PipelineDemo } from "@/components/pipeline-demo";
import { RewardChart } from "@/components/reward-chart";

export function generateStaticParams() {
  return caseStudies.map((p) => ({ slug: p.slug }));
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  const p = caseStudies.find((x) => x.slug === slug);
  return p ? pageMeta(`${p.title}, Tejas Thange`, p.summary, `/work/${p.slug}`) : {};
}

function Media({ slug }: { slug: string }) {
  if (slug === "docqa") return <div className="card p-5 md:p-8"><PipelineDemo /></div>;
  if (slug === "bipedal-agents") return <div className="card p-5 md:p-8"><RewardChart /></div>;
  const imgs =
    slug === "ganscape"
      ? { list: ["/work/ganscape-0000.webp", "/work/ganscape-0003.webp"], alt: "A height map generated by GanScape, rendered as relief", cols: "md:grid-cols-2", note: "Height maps generated by the model, rendered as relief maps." }
      : { list: ["/work/pest-2.jpg", "/work/pest-1.jpg", "/work/pest-3.jpg"], alt: "A crop pest detected by the model, with bounding box and confidence", cols: "grid-cols-3", note: "Real predictions from the model, with the boxes and confidence scores it drew." };
  return (
    <figure>
      <div className={`grid gap-3 ${imgs.cols}`}>
        {imgs.list.map((src) => (
          <div key={src} className="relative aspect-square overflow-hidden rounded-[20px] border border-line">
            <Image src={src} alt={imgs.alt} fill sizes="(min-width: 768px) 50vw, 100vw" className="object-cover" />
          </div>
        ))}
      </div>
      <figcaption className="mt-3 text-[13px] text-muted">{imgs.note}</figcaption>
    </figure>
  );
}

export default async function ProjectPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const index = caseStudies.findIndex((x) => x.slug === slug);
  if (index === -1) notFound();
  const p = caseStudies[index];
  const next = caseStudies[(index + 1) % caseStudies.length];

  return (
    <article className="mx-auto max-w-[1200px] px-4 pb-24 pt-10 md:px-8 md:pt-14">
      <Link href="/work" className="group inline-flex items-center gap-2 rounded-full py-1.5 text-[14px] font-medium text-muted transition-colors duration-200 hover:text-ink">
        <ArrowLeft size={15} className="transition-transform duration-300 ease-out group-hover:-translate-x-0.5" />
        All work
      </Link>

      <header className="mt-10 grid gap-8 md:mt-12 md:grid-cols-12">
        <div className="enter md:col-span-8">
          <p className="text-[15px] text-muted">{p.kind}</p>
          <h1 className="mt-2 font-display text-[clamp(42px,6vw,80px)] font-extrabold leading-[1.02] tracking-[-0.035em]">{p.title}</h1>
          <p className="mt-5 max-w-[44ch] text-pretty text-[clamp(18px,1.6vw,21px)] leading-[1.5] text-ink-2">{p.summary}</p>
        </div>
        <div className="enter flex flex-col justify-end gap-5 md:col-span-4" style={{ "--d": 1 } as React.CSSProperties}>
          <TechRow names={p.tools} size={40} />
          <p className="text-[14.5px] leading-relaxed text-ink-2"><span className="text-muted">Techniques: </span>{p.techniques.join(", ")}</p>
          {p.code && (
            <a href={p.code} target="_blank" rel="noopener" className="btn btn-secondary w-fit">
              <GithubLogo size={17} /> View the code
            </a>
          )}
        </div>
      </header>

      <div className="enter mt-12 md:mt-16" style={{ "--d": 2 } as React.CSSProperties}>
        <Media slug={p.slug} />
      </div>

      <div className="mt-16 grid gap-x-12 gap-y-10 md:mt-24 md:grid-cols-12">
        <h2 className="reveal font-display text-[24px] font-bold tracking-[-0.02em] md:col-span-4">The problem</h2>
        <p className="reveal max-w-[62ch] text-[17px] leading-[1.75] text-ink-2 md:col-span-8">{p.problem}</p>

        <h2 className="reveal font-display text-[24px] font-bold tracking-[-0.02em] md:col-span-4">How I built it</h2>
        <ol className="reveal max-w-[62ch] space-y-5 md:col-span-8">
          {p.approach.map((step, i) => (
            <li key={i} className="grid grid-cols-[26px_1fr] gap-3 text-[17px] leading-[1.75] text-ink-2">
              <span className="pt-[4px] font-mono text-[13px] text-accent">{String(i + 1).padStart(2, "0")}</span>
              <span>{step}</span>
            </li>
          ))}
        </ol>

        {p.result && (
          <>
            <h2 className="reveal font-display text-[24px] font-bold tracking-[-0.02em] md:col-span-4">Result</h2>
            <p className="reveal max-w-[62ch] text-[17px] leading-[1.75] text-ink md:col-span-8">{p.result}</p>
          </>
        )}
      </div>

      <Link href={`/work/${next.slug}`} className="card group mt-24 flex items-center justify-between gap-6 px-6 py-8 transition-colors duration-300 hover:border-line-2 md:mt-28 md:px-10">
        <span>
          <span className="block text-[14px] text-muted">Next project</span>
          <span className="mt-1 block font-display text-[clamp(24px,3vw,36px)] font-bold tracking-[-0.025em]">{next.title}</span>
        </span>
        <span className="btn btn-secondary btn-sm shrink-0">Open</span>
      </Link>
    </article>
  );
}
