// Logo registry. Full-colour Devicon logos where they exist, brand-coloured Simple Icons otherwise.
// `mono` logos are black or near-black, so they are drawn in the text colour to stay visible in both themes.

export type Tech = { file: string; mono?: boolean };

export const tech: Record<string, Tech> = {
  Python: { file: "python" },
  PyTorch: { file: "pytorch" },
  "Scikit-learn": { file: "sklearn" },
  OpenCV: { file: "opencv" },
  NumPy: { file: "numpy" },
  Pandas: { file: "pandas" },
  Matplotlib: { file: "matplotlib" },
  SciPy: { file: "scipy" },
  "ONNX Runtime": { file: "onnx" },
  Whisper: { file: "openai", mono: true },
  "Hugging Face": { file: "huggingface" },
  Ultralytics: { file: "ultralytics" },
  Jupyter: { file: "jupyter" },
  Colab: { file: "colab" },
  LangChain: { file: "langchain" },
  LangGraph: { file: "langgraph" },
  Gemini: { file: "gemini" },
  Claude: { file: "claude" },
  "Claude Code": { file: "claude" },
  Codex: { file: "openai", mono: true },
  FastAPI: { file: "fastapi" },
  Streamlit: { file: "streamlit" },
  "Next.js": { file: "nextjs" },
  React: { file: "react" },
  TypeScript: { file: "typescript" },
  Vite: { file: "vite" },
  "Tailwind CSS": { file: "tailwind" },
  Motion: { file: "motion", mono: true },
  Vercel: { file: "vercel", mono: true },
  AWS: { file: "aws" },
  Git: { file: "git" },
  GitHub: { file: "github", mono: true },
  "VS Code": { file: "vscode" },
  Cursor: { file: "cursor", mono: true },
  WordPress: { file: "wordpress" },
  Jira: { file: "jira" },
  MySQL: { file: "mysql" },
  MongoDB: { file: "mongodb" },
  "Raspberry Pi": { file: "raspberrypi" },
  Zoho: { file: "zoho" },
};
