"use client";

import Image from "next/image";
import { useState } from "react";
import { AnimatePresence, motion, useMotionValue, useSpring } from "motion/react";
import { Plus } from "@phosphor-icons/react";
import { experience } from "@/content/site";

type Preview = { kind: "image"; src: string; caption: string } | { kind: "text"; title: string; body: string; mono?: boolean };

const PREVIEWS: Record<string, Preview> = {
  symbiosis: { kind: "text", title: "Symbiosis Institute of Technology", body: "B.Tech, Artificial Intelligence and Machine Learning, 2022 to 2026. Statistics and EDA up to deep learning, GANs and LLMs, plus a Google Data Analytics certificate on the side." },
  pest: { kind: "image", src: "/work/pest-2.jpg", caption: "Output from the pest detector" },
  gan: { kind: "image", src: "/work/ganscape-0003.webp", caption: "A height map generated by GanScape" },
  idk: { kind: "text", title: "DocQA", body: "Upload a PDF and ask it questions, including about its tables and images. Each answer points back to the page it came from." },
  upbringing: { kind: "text", title: "Upbringing Technologies", body: "Built and shipped the company website in Next.js on Vercel, plus the chatbot's knowledge base." },
  mimic: { kind: "text", title: "Mimic Productions", body: "AI Programming Intern, remote, since July 2026. Working on the RAG backend behind the Mimic Minds AI avatars." },
  speech: { kind: "text", title: "Speech models, on a laptop", body: "Open-source speech-to-text and text-to-speech, tested for whether they could run on edge devices instead of a server." },
};

function Hover({ id, children, onShow }: { id: string; children: React.ReactNode; onShow: (id: string | null, at?: DOMRect) => void }) {
  return (
    <span
      tabIndex={0}
      onPointerEnter={(e) => e.pointerType === "mouse" && onShow(id)}
      onPointerLeave={() => onShow(null)}
      onFocus={(e) => onShow(id, e.currentTarget.getBoundingClientRect())}
      onBlur={() => onShow(null)}
      className="cursor-default rounded-[4px] text-ink underline decoration-line-2 decoration-[1.5px] underline-offset-[5px] transition-[text-decoration-color] duration-200 hover:decoration-ink"
    >
      {children}
    </span>
  );
}

const BLADE = "M16 0 C17.4 12 22.5 34 24.6 54 C25 58 23.4 61 19.6 62.6 L18.4 64 H13.6 L12.4 62.6 C8.6 61 7 58 7.4 54 C9.5 34 14.6 12 16 0 Z";

/** The timeline as a spear, after an Indian bhala: a long triangular blade with engraved fullers and a
 *  carved scroll at its base, a socket turned with moulded collars, the shaft, and an iron butt-cap.
 *  Its metal (silver, gold or red) is picked per visit, like the card glow; the colours live in globals.css. */
function Spear() {
  return (
    <div aria-hidden className="spear pointer-events-none absolute inset-y-0 left-0 flex w-9 flex-col items-center">
      <svg viewBox="0 0 32 124" className="spear-head h-[140px] w-9 shrink-0 overflow-visible">
        <defs>
          <linearGradient id="blade" x1="0" x2="1" y1="0" y2="0">
            <stop offset="0" style={{ stopColor: "var(--blade-edge)" }} />
            <stop offset="0.5" style={{ stopColor: "var(--blade-core)" }} />
            <stop offset="0.5" style={{ stopColor: "var(--blade-core-2)" }} />
            <stop offset="1" style={{ stopColor: "var(--blade-edge-2)" }} />
          </linearGradient>
          <linearGradient id="glint" x1="0" x2="0" y1="0" y2="1">
            <stop offset="0" stopColor="white" stopOpacity="0" />
            <stop offset="0.5" stopColor="white" stopOpacity="0.85" />
            <stop offset="1" stopColor="white" stopOpacity="0" />
          </linearGradient>
          <clipPath id="blade-clip"><path d={BLADE} /></clipPath>
        </defs>
        {/* blade, lit from the left so the central ridge reads */}
        <path d={BLADE} fill="url(#blade)" />
        <g fill="none" stroke="var(--engrave)" strokeLinecap="round">
          {/* fullers engraved along both edges */}
          <path d="M16 6 C17.1 16 21 36 22.2 53 C22.4 56 21 58 18 59.2" strokeWidth="0.7" />
          <path d="M16 6 C14.9 16 11 36 9.8 53 C9.6 56 11 58 14 59.2" strokeWidth="0.7" />
          {/* the central ridge */}
          <path d="M16 3 V56" strokeWidth="0.6" />
          {/* carved double scroll at the base of the blade */}
          <path d="M16 61.4 C16 58.4 12.8 57.6 12.4 59.6 C12.1 61 13.9 61.5 14.4 60.4" strokeWidth="0.75" />
          <path d="M16 61.4 C16 58.4 19.2 57.6 19.6 59.6 C19.9 61 18.1 61.5 17.6 60.4" strokeWidth="0.75" />
        </g>
        {/* the energy arriving: light running up the blade to the point */}
        <g clipPath="url(#blade-clip)">
          <rect className="spear-glint" x="0" y="-30" width="32" height="22" fill="url(#glint)" />
        </g>
        {/* socket, turned with moulded collars, tapering into the shaft so the joint is seamless */}
        <g fill="var(--socket)">
          <path d="M13.6 64 H18.4 V67 H13.6 Z" />
          <path d="M12.8 70 H19.2 L18.6 84 H13.4 Z" />
          <path d="M13.2 86.6 H18.8 L18.2 100 H13.8 Z" />
          <path d="M13.6 102.4 H18.4 L17.1 124 H14.9 Z" />
        </g>
        <g fill="var(--collar)">
          <rect x="11.8" y="67" width="8.4" height="3" rx="1.2" />
          <rect x="12" y="84" width="8" height="2.6" rx="1.1" />
          <rect x="12.6" y="100" width="6.8" height="2.4" rx="1" />
        </g>
        <g stroke="white" strokeOpacity="0.28" strokeWidth="0.5">
          <path d="M12.6 67.6 H19.4" /><path d="M12.8 84.5 H19.2" /><path d="M13.4 100.5 H18.6" />
        </g>
      </svg>
      {/* shaft: energy rises through it from the butt-cap to the blade (see .spear-shaft in globals.css) */}
      <span className="spear-shaft relative w-[2.5px] flex-1 rounded-full bg-[linear-gradient(to_bottom,var(--shaft-top),var(--shaft-bottom))]" />
      {/* butt-cap */}
      <svg viewBox="0 0 28 16" className="h-5 w-9 shrink-0"><path d="M11 0 H17 L15.5 12 L14 16 L12.5 12 Z" fill="var(--cap)" /></svg>
    </div>
  );
}

export function About() {
  const [show, setShow] = useState<string | null>(null);
  const [open, setOpen] = useState(0);
  const mx = useMotionValue(0), my = useMotionValue(0);
  const x = useSpring(mx, { stiffness: 400, damping: 35 }), y = useSpring(my, { stiffness: 400, damping: 35 });
  const preview = show ? PREVIEWS[show] : null;
  // Keyboard or tap focus has no pointer position, so anchor the card under the phrase instead.
  const onShow = (id: string | null, at?: DOMRect) => {
    if (at) { const left = Math.min(at.left, window.innerWidth - 280); mx.jump(left); my.jump(at.bottom + 10); x.jump(left); y.jump(at.bottom + 10); }
    setShow(id);
  };

  return (
    <div className="grid gap-14 md:grid-cols-12 md:gap-12">
      <div
        className="md:col-span-6"
        onPointerMove={(e) => { mx.set(e.clientX + 18); my.set(e.clientY + 18); }}
      >
        <div className="max-w-[56ch] space-y-6 text-[18px] leading-[1.75] text-ink-2">
          <p>
            I finished my B.Tech in AI and Machine Learning at <Hover id="symbiosis" onShow={onShow}>Symbiosis Institute of Technology</Hover>,
            Pune, in 2026. Most of my projects are about getting a model to work outside a notebook: <Hover id="pest" onShow={onShow}>a pest
            detector that runs on a Raspberry Pi</Hover>, <Hover id="gan" onShow={onShow}>a GAN that generates 3D terrain</Hover>, and{" "}
            <Hover id="idk" onShow={onShow}>a system that answers questions from PDFs</Hover>.
          </p>
          <p>
            Right now I&apos;m an AI programming intern at <Hover id="mimic" onShow={onShow}>Mimic Productions</Hover>. I work on the
            backend that feeds documents and websites into their AI avatars, and I&apos;ve{" "}
            <Hover id="speech" onShow={onShow}>tested speech models</Hover> small enough to run on the device itself.
          </p>
          <p>
            Before that I was at <Hover id="upbringing" onShow={onShow}>Upbringing Technologies</Hover>, where I built the company
            website. That&apos;s when I started building the frontend for my own projects too, so a few projects here are full websites.
          </p>
          <p>Outside work I draw portraits and follow cricket and football.</p>
        </div>
      </div>

      <ol className="relative pt-[134px] md:col-span-6 md:-mt-[140px]">
        <Spear />
        {experience.map((e, i) => {
          const isOpen = open === i;
          return (
            <li key={e.org} className="relative pb-5 pl-11 last:pb-10 sm:pl-14">
              {/* a lashing bound round the shaft marks each entry */}
              <span aria-hidden className="absolute left-[18px] top-[42px] grid -translate-x-1/2 place-items-center">
                <span className={`block size-[13px] rotate-45 rounded-[3px] border-[1.5px] transition-[background-color,border-color,box-shadow] duration-300 ${isOpen ? "border-[var(--spear)] bg-[var(--spear)] shadow-[0_0_0_5px_color-mix(in_oklab,var(--spear)_16%,transparent)]" : "border-[color-mix(in_oklab,var(--spear)_50%,transparent)] bg-bg"}`} />
              </span>
              <div
                className={`job-card rounded-[22px] border transition-[background-color,border-color,box-shadow] duration-300 ${isOpen ? "is-open border-line-2 bg-surface" : "border-line bg-surface/40 hover:border-line-2 hover:bg-surface"}`}
              >
                <button type="button" onClick={() => setOpen(isOpen ? -1 : i)} aria-expanded={isOpen} className="flex w-full cursor-pointer items-start gap-3 p-4 text-left sm:gap-4 sm:p-5">
                  <span
                    aria-hidden
                    className="grid size-10 shrink-0 place-items-center rounded-[12px] sm:size-12 sm:rounded-[14px] shadow-[inset_0_0_0_1px_rgb(255_255_255/0.08),0_1px_2px_rgb(0_0_0/0.3)]"
                    style={{ background: e.logo.tile, padding: e.logo.pad }}
                  >
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img src={e.logo.src} alt="" className="h-full w-full object-contain" />
                  </span>
                  <span className="min-w-0 flex-1">
                    <span className="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-1">
                      <span className="font-display text-[21px] font-bold leading-tight tracking-[-0.015em] text-ink">{e.org}</span>
                      <span className="font-mono text-[12.5px] text-ink">{e.period}</span>
                    </span>
                    <span className="mt-1 block text-[14.5px] text-ink-2">
                      {e.role} <span className="text-muted">·</span> {e.place}
                    </span>
                    <span className="mt-2.5 block text-[14.5px] leading-relaxed text-ink-2">{e.summary}</span>
                  </span>
                  <Plus size={16} className={`mt-1.5 shrink-0 text-ink-2 transition-transform duration-300 ease-out ${isOpen ? "rotate-45" : ""}`} />
                </button>
                <AnimatePresence initial={false}>
                  {isOpen && (
                    <motion.div
                      initial={{ height: 0, opacity: 0, filter: "blur(4px)" }}
                      animate={{ height: "auto", opacity: 1, filter: "blur(0px)" }}
                      exit={{ height: 0, opacity: 0, filter: "blur(4px)" }}
                      transition={{ type: "spring", duration: 0.45, bounce: 0 }}
                      className="overflow-hidden"
                    >
                      <div className="mx-4 border-t border-line pb-5 pt-4 sm:mx-5 sm:pl-16">
                        <ul className="space-y-3">
                          {e.points.map((pt) => (
                            <li key={pt} className="relative pl-5 text-[15px] leading-relaxed text-ink-2">
                              <span aria-hidden className="absolute left-0 top-[0.62em] size-[6px] rotate-45 rounded-[1.5px] bg-[var(--spear)] opacity-80" />
                              {pt}
                            </li>
                          ))}
                        </ul>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            </li>
          );
        })}
      </ol>

      <AnimatePresence>
        {preview && (
          <motion.div
            key={show}
            aria-hidden
            initial={{ opacity: 0, scale: 0.94, filter: "blur(6px)" }}
            animate={{ opacity: 1, scale: 1, filter: "blur(0px)" }}
            exit={{ opacity: 0, scale: 0.96, filter: "blur(4px)", transition: { duration: 0.12 } }}
            transition={{ type: "spring", duration: 0.35, bounce: 0.1 }}
            style={{ x, y }}
            className="pointer-events-none fixed left-0 top-0 z-50 w-[260px] origin-top-left overflow-hidden rounded-[16px] border border-line-2 bg-raised p-2 shadow-[0_20px_50px_-15px_rgb(0_0_0/0.55)]"
          >
            {preview.kind === "image" ? (
              <>
                <div className="relative aspect-[4/3] overflow-hidden rounded-[11px]">
                  <Image src={preview.src} alt="" fill sizes="260px" className="object-cover" />
                </div>
                <p className="px-1.5 pb-0.5 pt-2 text-[12.5px] text-ink-2">{preview.caption}</p>
              </>
            ) : (
              <div className="p-2.5">
                <p className="font-display text-[15px] font-bold tracking-[-0.01em] text-ink">{preview.title}</p>
                <p className={`mt-1.5 text-[13.5px] leading-relaxed text-ink-2 ${preview.mono ? "font-mono" : ""}`}>{preview.body}</p>
              </div>
            )}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
