import Image from "next/image";
import Link from "next/link";
import { GithubLogo, Globe } from "@phosphor-icons/react/dist/ssr";
import { PipelineDemo } from "./pipeline-demo";
import { RewardChart } from "./reward-chart";
import { SpotCard } from "./spot-card";
import { GlowArea } from "./glow-area";
import { TechRow } from "./tech-logo";
import { builds, caseStudies } from "@/content/site";

export function SectionHead({ title, sub, as: H = "h2" }: { title: string; sub?: string; as?: "h1" | "h2" }) {
  return (
    <div className="reveal">
      <H className="font-display text-[clamp(34px,4vw,52px)] font-bold leading-[1.05] tracking-[-0.03em]">{title}</H>
      {sub && <p className="mt-3 max-w-[54ch] text-[17px] text-ink-2">{sub}</p>}
    </div>
  );
}

/** Media sits inset in the card (radius 22 - 8 = 14) so the corners stay concentric. */
function WorkCard({
  span, media, kind, title, summary, tools, slug, code, live,
}: {
  span: string; media: React.ReactNode; kind: string; title: string; summary: string; tools: string[];
  slug?: string; code?: string; live?: string;
}) {
  return (
    <SpotCard className={`reveal card group flex flex-col p-2 ${span}`}>
      <div className="overflow-hidden rounded-[14px] border border-line bg-bg">{media}</div>
      <GlowArea className="-mx-2 -mb-2 flex flex-1 flex-col rounded-b-[22px] px-6 pb-6 pt-5 md:px-7">
        <p className="text-[13px] text-muted">{kind}</p>
        <h3 className="mt-1 font-display text-[26px] font-bold leading-tight tracking-[-0.025em]">
          {slug ? (
            <Link href={`/work/${slug}`} className="bg-[linear-gradient(currentColor,currentColor)] bg-[length:0%_1.5px] bg-[position:0_100%] bg-no-repeat transition-[background-size] duration-500 ease-out hover:bg-[length:100%_1.5px]">
              {title}
            </Link>
          ) : title}
        </h3>
        <p className="mt-2 max-w-[54ch] text-[15.5px] leading-relaxed text-ink-2">{summary}</p>
        <div className="mt-auto flex flex-wrap items-end justify-between gap-4 pt-6">
          <TechRow names={tools} />
          <div className="flex items-center gap-1.5">
            {slug && <Link href={`/work/${slug}`} className="btn btn-secondary btn-sm">Case study</Link>}
            {live && (
              <a href={live} target="_blank" rel="noopener" className="btn btn-secondary btn-sm">
                <Globe size={15} /> Live site
              </a>
            )}
            {code && (
              <a href={code} target="_blank" rel="noopener" aria-label={`${title} source code on GitHub`} className="btn btn-secondary btn-sm !px-2.5">
                <GithubLogo size={16} />
              </a>
            )}
          </div>
        </div>
      </GlowArea>
    </SpotCard>
  );
}

const cs = Object.fromEntries(caseStudies.map((c) => [c.slug, c]));

const media: Record<string, React.ReactNode> = {
  docqa: <div className="p-4 md:p-5"><PipelineDemo /></div>,
  ganscape: (
    <div className="grid grid-cols-2 gap-1 p-1">
      {["/work/ganscape-0000.webp", "/work/ganscape-0003.webp"].map((src) => (
        <div key={src} className="relative aspect-[4/5] overflow-hidden rounded-[10px]">
          <Image src={src} alt="A height map generated by GanScape, rendered as relief" fill sizes="(min-width: 768px) 230px, 48vw"
            className="object-cover transition-transform duration-700 ease-out group-hover:scale-[1.04]" />
        </div>
      ))}
    </div>
  ),
  "pest-detection": (
    <div className="grid grid-cols-3 grid-rows-2 gap-1 p-1">
      {["/work/pest-2.jpg", "/work/pest-1.jpg", "/work/pest-3.jpg"].map((src, i) => (
        <div key={src} className={`relative overflow-hidden rounded-[10px] ${i === 0 ? "col-span-2 row-span-2 aspect-square" : "aspect-square"}`}>
          <Image src={src} alt="A crop pest found by the detector, with its bounding box and confidence" fill
            sizes={i === 0 ? "(min-width: 768px) 300px, 64vw" : "160px"} className="object-cover transition-transform duration-700 ease-out group-hover:scale-[1.04]" />
        </div>
      ))}
    </div>
  ),
  "bipedal-agents": <div className="p-4 md:p-5"><RewardChart /></div>,
};

export function ProjectCard({ slug, span }: { slug: string; span: string }) {
  const p = cs[slug];
  return <WorkCard span={span} kind={p.kind} title={p.title} summary={p.summary} tools={p.tools} slug={p.slug} code={p.code} media={media[slug]} />;
}

export function BuildCards() {
  return builds.map((b) => (
    <WorkCard
      key={b.title} span="md:col-span-6" kind={b.kind} title={b.title} summary={b.summary} tools={b.tools} code={b.code} live={b.live}
      media={
        <div className="aspect-[16/10] overflow-hidden">
          <Image src={b.image} alt={`Homepage of ${b.title}`} width={1440} height={900} sizes="(min-width: 768px) 560px, 100vw"
            className="h-full w-full object-cover object-top transition-transform duration-700 ease-out group-hover:scale-[1.025]" />
        </div>
      }
    />
  ));
}
